-- ============================================================
-- USERS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL UNIQUE
);

-- ============================================================
-- REQUESTS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description  VARCHAR(1000)               NOT NULL,
    requestor_id BIGINT                      NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_request_to_user FOREIGN KEY (requestor_id) REFERENCES users (id) ON DELETE CASCADE
);

-- ============================================================
-- ITEMS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255)  NOT NULL,
    description  VARCHAR(1000) NOT NULL,
    is_available BOOLEAN       NOT NULL DEFAULT TRUE,
    owner_id     BIGINT        NOT NULL,
    request_id   BIGINT,
    CONSTRAINT fk_item_to_user FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_item_to_request FOREIGN KEY (request_id) REFERENCES requests (id) ON DELETE SET NULL
);

-- ============================================================
-- BOOKINGS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS bookings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id    BIGINT                      NOT NULL,
    booker_id  BIGINT                      NOT NULL,
    status     VARCHAR(20)                 NOT NULL DEFAULT 'WAITING',
    CONSTRAINT fk_booking_to_item FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE,
    CONSTRAINT fk_booking_to_user FOREIGN KEY (booker_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT check_dates CHECK (end_date > start_date)
);

-- ============================================================
-- COMMENTS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text      VARCHAR(1000)               NOT NULL,
    item_id   BIGINT                      NOT NULL,
    author_id BIGINT                      NOT NULL,
    created   TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_comment_to_item FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE,
    CONSTRAINT fk_comment_to_user FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE
);

-- ============================================================
-- INDEXES (для производительности)
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_items_owner ON items (owner_id);
CREATE INDEX IF NOT EXISTS idx_items_request ON items (request_id);
CREATE INDEX IF NOT EXISTS idx_items_available ON items (is_available);

CREATE INDEX IF NOT EXISTS idx_bookings_item ON bookings (item_id);
CREATE INDEX IF NOT EXISTS idx_bookings_booker ON bookings (booker_id);
CREATE INDEX IF NOT EXISTS idx_bookings_status ON bookings (status);
CREATE INDEX IF NOT EXISTS idx_bookings_dates ON bookings (start_date, end_date);

CREATE INDEX IF NOT EXISTS idx_comments_item ON comments (item_id);
CREATE INDEX IF NOT EXISTS idx_comments_author ON comments (author_id);

CREATE INDEX IF NOT EXISTS idx_requests_requestor ON requests (requestor_id);
CREATE INDEX IF NOT EXISTS idx_requests_created ON requests (created DESC);